version: '3.6'
services:
  #Elastic
  mjl-es-01:
      image: 'docker.elastic.co/elasticsearch/elasticsearch:8.1.0'
      container_name: 'mjl-es-01'
      hostname: 'mjl-es-01'
      environment:
        - ELASTIC_PASSWORD=password
        - discovery.type=single-node
        - node.name=MJLNode01
        - "ES_JAVA_OPTS=-Xms512m -Xmx1800m"
      ports:
        - '9200:9200'
        - '9300:9300'
      ulimits:
         memlock:
            soft: -1
            hard: -1
      networks:
        - es-mjl
      deploy:
          resources:
            limits:
              memory: 2g
            reservations:
              memory: 1g
  mjl-kibana:
      image: 'docker.elastic.co/kibana/kibana:7.7.0'
      container_name: 'mjl-kibana'
      hostname: 'mjl-kibana'
      environment:
        - SERVER_NAME=mjl-kibana
        - ELASTICSEARCH_HOSTS=http://mjl-es-instance:9200
      ports:
        - '5601:5601'
      networks:
        - es-mjl
      extra_hosts:
        - 'mjl-es-instance:192.168.1.240'
      deploy:
          resources:
            limits:
              memory: 1g
            reservations:
              memory: 500m
  #Kafka
  mjl-kafka-zookeeper:
      image: 'johnnypark/kafka-zookeeper'
      container_name: 'mjl-kafka'
      hostname: 'mjl-kakfa'
      environment:
        - ADVERTISED_HOST=127.0.0.1
        - NUM_PARTITIONS=8
      ports:
        - '2181:2181'
        - '9092:9092'
      networks:
        - kafka-mjl
networks:
  es-mjl:
    driver: bridge
  kafka-mjl:
    driver: bridge
