# CircleCI v2.1 Config
version: 2.1

##
# orbs
#
# Orbs used in this pipeline
##
orbs:
  anchore: anchore/anchore-engine@1.9.0
  slack: circleci/slack@4.12.5 # Ref: https://github.com/mojaloop/ci-config/tree/main/slack-templates
  pr-tools: mojaloop/pr-tools@0.1.10 # Ref: https://github.com/mojaloop/ci-config/
  gh: circleci/github-cli@2.2.0

# this allows you to use CircleCI's dynamic configuration feature
#setup: true

##
# Yaml anchors
#
##
defaults_configure_git: &defaults_configure_git
  name: Configure git
  command: |
    git config user.email ${GIT_CI_EMAIL}
    git config user.name ${GIT_CI_USER}

defaults_npm_auth: &defaults_npm_auth
  name: Update NPM registry auth token
  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

## Default 'default-machine' executor dependencies
defaults_machine_Dependencies: &defaults_machine_Dependencies |
  ## Add Package Repos
  ## Ref: https://docs.confluent.io/platform/current/installation/installing_cp/deb-ubuntu.html#get-the-software
  wget -qO - https://packages.confluent.io/deb/7.4/archive.key | sudo apt-key add -
  sudo add-apt-repository -y "deb https://packages.confluent.io/clients/deb $(lsb_release -cs) main"

  ## Install deps
  sudo apt install -y librdkafka-dev curl bash musl-dev libsasl2-dev
  sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

defaults_configure_nvm: &defaults_configure_nvm |
    cd $HOME
    export ENV_DOT_PROFILE=$HOME/.profile
    touch $ENV_DOT_PROFILE
    echo "1. Check/Set NVM_DIR env variable"
    if [ -z "$NVM_DIR" ]; then
      export NVM_DIR="$HOME/.nvm"
      echo "==> NVM_DIR has been exported - $NVM_DIR"
    else
      echo "==> NVM_DIR already exists - $NVM_DIR"
    fi
    echo "2. Check/Set NVMRC_VERSION env variable"
    if [ -z "$NVMRC_VERSION" ]; then
      echo "==> Configuring NVMRC_VERSION!"
      export NVMRC_VERSION=$(cat $CIRCLE_WORKING_DIRECTORY/.nvmrc)
      echo "export NVMRC_VERSION=$NVMRC_VERSION" >> $ENV_DOT_PROFILE
    fi
    echo "3. Configure NVM"
    ## Lets check if an existing NVM_DIR exists, if it does lets skil
    if [ -e "$NVM_DIR" ]; then
      echo "==> $NVM_DIR exists. Skipping steps 3!"
      # echo "5. Executing $NVM_DIR/nvm.sh"
      # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    else
      echo "==> $NVM_DIR does not exists. Executing steps 4-5!"
      echo "4. Installing NVM"
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      echo "5. Executing $NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    fi
    ## Ref: https://github.com/nvm-sh/nvm/issues/1102#issuecomment-550572252
    if [ ! -z "$NVM_ARCH_UNOFFICIAL_OVERRIDE" ]; then
      echo "==> Handle NVM_ARCH_UNOFFICIAL_OVERRIDE=$NVM_ARCH_UNOFFICIAL_OVERRIDE!"
      echo "nvm_get_arch() { nvm_echo \"${NVM_ARCH_UNOFFICIAL_OVERRIDE}\"; }" >> $ENV_DOT_PROFILE
      echo "export NVM_NODEJS_ORG_MIRROR=https://unofficial-builds.nodejs.org/download/release" >> $ENV_DOT_PROFILE
      source $ENV_DOT_PROFILE
    fi
    echo "6. Setup Node version"
    if [ -n "$NVMRC_VERSION" ]; then
      echo "==> Installing Node version: $NVMRC_VERSION"
      nvm install $NVMRC_VERSION
      nvm alias default $NVMRC_VERSION
      nvm use $NVMRC_VERSION
      cd $CIRCLE_WORKING_DIRECTORY
    else
      echo "==> ERROR - NVMRC_VERSION has not been set! - NVMRC_VERSION: $NVMRC_VERSION"
      exit 1
    fi
##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: &workingDirVar /home/circleci/project
    docker:
      - image: mojaloop/node-20.10.0-builder:0.0.2

  default-machine:
    working_directory: *workingDirVar
    machine:
      image: ubuntu-2204:2023.04.2
      docker_layer_caching: true

jobs:
  setup:
    executor: default-docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package.json" }}
      - run: BUILD_LIBRDKAFKA=0 npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-cache-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .
  build:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run build
      - save_cache:
          paths:
            - packages
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .
  lint:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run lint

  test-unit:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run:
          name: Execute unit tests
          command: npm run test:unit
      # store workspace for the coverage-report step
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .

  test-integration:
    executor: default-machine
    steps:
      - attach_workspace:
          at: *workingDirVar
      # - run:
      #     name: Install curl
      #     command: |
      #       apk update
      #       apk add curl
      #
      - run:
          name: Install general dependencies
          command: *defaults_machine_Dependencies
      - run:
          name: Configure NVM
          command: *defaults_configure_nvm
      - run: BUILD_LIBRDKAFKA=0 npm install
      - run:
          name: Run Infra and Execute integration tests
          command: |
            SAVED_DIR=$(pwd)
            cd ./test/scripts/docker-compose-infra
            ./infra.sh
            cd $SAVED_DIR
            sleep 10
            docker ps
            npm run test:integration
      # store workspace for the coverage-report step
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .

  coverage-report:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run:
          name: Ensure coverage directory exists (FIXME find better way)
          command: mkdir -p ./coverage
      - run:
          name: Merge json coverage files
          command: npm run coverage:merge
      - run:
          name: Generate coverage report
          command: npm run coverage:gen-report
      - store_artifacts:
          path: coverage

  publish:
    executor: default-machine
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run:
          <<: *defaults_configure_git
      - run:
          name: Add github.com to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          <<: *defaults_npm_auth
      - run:
          name: Configure NPM registry
          command: npm config set registry https://registry.npmjs.org/
      - run:
          name: Detect changes, publishing npm and publish docker images
          no_output_timeout: 30m
          command: chmod +x .circleci/*.sh && .circleci/publish.sh

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - setup:
          context: org-global
      - build:
          context: org-global
          requires:
            - setup
      - lint:
          context: org-global
          requires:
            - build
      - test-unit:
          context: org-global
          requires:
            - lint
      - test-integration:
          context: org-global
          requires:
            - lint
      - coverage-report:
          context: org-global
          requires:
            - test-unit
            - test-integration
      - publish:
          context: org-global
          filters:
            branches:
              only: main
          requires:
            - test-unit
